In [1]:
import pandas as pd

In [2]:
cluster = pd.read_csv("cluster.csv")
cluster.head()

,ID Kabupaten,No.,Tanggal Kejadian,Kejadian,Lokasi,Kabupaten,Provinsi,Kronologi & Dokumentasi,Penyebab,Meninggal,Hilang,Terluka,Rumah Rusak,Fasum Rusak,korban_jiwa,kerusakan,Clusters,cluster
0,1601,1,31/12/2021,BANJIR,Kec. Lubuk Batang Ds. Gunung Meraksa,OGAN KOMERING ULU,SUMATERA SELATAN,NaN,● Dipicu oleh hujan dengan intensitas tinggi d...,0,0,0,0,0,0,0,0,0
1,1111,2,31/12/2021,BANJIR,Kec. Dewantara Gp. Tambon Tunong Gp. Uteun ge...,ACEH UTARA,ACEH,NaN,● Dipicu oleh hujan dengan intensitas tinggi d...,3,0,0,1,0,3,1,0,0
2,1213,3,31/12/2021,BANJIR,Kec. Pematang Jaya Ds. Damar Condong,LANGKAT,SUMATERA UTARA,NaN,● Dipicu oleh dengan intensitas curah hujan ya...,0,0,0,0,0,0,0,0,0
3,1221,4,31/12/2021,BANJIR,● Kec. Batang Lobu Sutam - Ds. Tanjung Baru - ...,PADANG LAWAS,SUMATERA UTARA,NaN,Dipicu hujan deras dengan durasi panjang menga...,0,0,0,637,1,0,638,0,0
4,3374,5,31/12/2021,BANJIR,Kec. Gayamsari Kel. Tambakrejo Kel. Kaligawe K...,KOTA SEMARANG,JAWA TENGAH,NaN,Dipicu hujan dengan intensitas tinggi di wilay...,0,0,0,0,0,0,0,0,0

In [3]:
koordinat = pd.read_csv("koordinat.csv")
koordinat.head()

,Unnamed: 0,Location,loc,point,lat,lon,altitude
0,0,"OGAN KOMERING ULU,SUMATERA SELATAN","Ogan Komering Ulu, Sumatera Selatan, Indonesia","(-4.1101012, 104.00828376734528, 0.0)",-4.110101,104.008284,0.0
1,1,"ACEH UTARA,ACEH","Aceh Utara, Aceh, Indonesia","(4.99119405, 97.1587368058996, 0.0)",4.991194,97.158737,0.0
2,2,"LANGKAT,SUMATERA UTARA","Langkat, Sumatera Utara, Indonesia","(3.8290501, 98.24827397454335, 0.0)",3.829050,98.248274,0.0
3,3,"PADANG LAWAS,SUMATERA UTARA","Padang Lawas, Sumatera Utara, 22774, Indonesia","(1.1565902000000001, 99.81080407051435, 0.0)",1.156590,99.810804,0.0
4,4,"KOTA SEMARANG,JAWA TENGAH","Gang Kelapa Gading, Wates, Ngaliyan, Kota Sema...","(-7.0197176, 110.3360514, 0.0)",-7.019718,110.336051,0.0

In [4]:
koordinat.shape

(2968, 7)

In [8]:
koordinat = koordinat.drop(columns = ["Unnamed: 0"])

In [9]:
koordinat.isnull().sum()

Location    0
loc         9
point       9
lat         9
lon         9
altitude    9
dtype: int64

In [10]:
cluster.isnull().sum()

ID Kabupaten                  0
No.                           0
Tanggal Kejadian              0
Kejadian                      0
Lokasi                       32
Kabupaten                     0
Provinsi                      0
Kronologi & Dokumentasi    2734
Penyebab                    482
Meninggal                     0
Hilang                        0
Terluka                       0
Rumah Rusak                   0
Fasum Rusak                   0
korban_jiwa                   0
kerusakan                     0
Clusters                      0
cluster                       0
dtype: int64

In [11]:
koordinat = koordinat.reset_index(drop=True)
cluster = cluster.reset_index(drop=True)

In [12]:
koordinat.head()

,Location,loc,point,lat,lon,altitude
0,"OGAN KOMERING ULU,SUMATERA SELATAN","Ogan Komering Ulu, Sumatera Selatan, Indonesia","(-4.1101012, 104.00828376734528, 0.0)",-4.110101,104.008284,0.0
1,"ACEH UTARA,ACEH","Aceh Utara, Aceh, Indonesia","(4.99119405, 97.1587368058996, 0.0)",4.991194,97.158737,0.0
2,"LANGKAT,SUMATERA UTARA","Langkat, Sumatera Utara, Indonesia","(3.8290501, 98.24827397454335, 0.0)",3.829050,98.248274,0.0
3,"PADANG LAWAS,SUMATERA UTARA","Padang Lawas, Sumatera Utara, 22774, Indonesia","(1.1565902000000001, 99.81080407051435, 0.0)",1.156590,99.810804,0.0
4,"KOTA SEMARANG,JAWA TENGAH","Gang Kelapa Gading, Wates, Ngaliyan, Kota Sema...","(-7.0197176, 110.3360514, 0.0)",-7.019718,110.336051,0.0

In [13]:
cluster.head()

,ID Kabupaten,No.,Tanggal Kejadian,Kejadian,Lokasi,Kabupaten,Provinsi,Kronologi & Dokumentasi,Penyebab,Meninggal,Hilang,Terluka,Rumah Rusak,Fasum Rusak,korban_jiwa,kerusakan,Clusters,cluster
0,1601,1,31/12/2021,BANJIR,Kec. Lubuk Batang Ds. Gunung Meraksa,OGAN KOMERING ULU,SUMATERA SELATAN,NaN,● Dipicu oleh hujan dengan intensitas tinggi d...,0,0,0,0,0,0,0,0,0
1,1111,2,31/12/2021,BANJIR,Kec. Dewantara Gp. Tambon Tunong Gp. Uteun ge...,ACEH UTARA,ACEH,NaN,● Dipicu oleh hujan dengan intensitas tinggi d...,3,0,0,1,0,3,1,0,0
2,1213,3,31/12/2021,BANJIR,Kec. Pematang Jaya Ds. Damar Condong,LANGKAT,SUMATERA UTARA,NaN,● Dipicu oleh dengan intensitas curah hujan ya...,0,0,0,0,0,0,0,0,0
3,1221,4,31/12/2021,BANJIR,● Kec. Batang Lobu Sutam - Ds. Tanjung Baru - ...,PADANG LAWAS,SUMATERA UTARA,NaN,Dipicu hujan deras dengan durasi panjang menga...,0,0,0,637,1,0,638,0,0
4,3374,5,31/12/2021,BANJIR,Kec. Gayamsari Kel. Tambakrejo Kel. Kaligawe K...,KOTA SEMARANG,JAWA TENGAH,NaN,Dipicu hujan dengan intensitas tinggi di wilay...,0,0,0,0,0,0,0,0,0